# Generated by Django 5.1.4 on 2024-12-24 06:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("price", models.IntegerField(default=0)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("M", "medium"),
                            ("S", "small"),
                            ("L", "large"),
                            ("XL", "extra large"),
                        ],
                        default="M",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SPORTS", "sports"),
                            ("WINTER", "winter"),
                            ("SUMMER", "summer"),
                        ],
                        default="SPORTS",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2024, 12, 24, 6, 47, 26, 1776),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shoppers.productdetails",
                    ),
                ),
            ],
        ),
    ]
