# Generated by Django 5.1.4 on 2024-12-24 07:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoppers", "0002_alter_customer_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shoppers.productdetails",
            ),
        ),
        migrations.AlterField(
            model_name="productdetails",
            name="created_on",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 12, 24, 7, 13, 23, 890158)
            ),
        ),
    ]
